# Generated by Django 3.0.6 on 2020-05-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_page',
        ),
    ]
