# Generated by Django 3.0.6 on 2020-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200523_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(upload_to='images/books_cover_pages/'),
        ),
    ]
