# Generated by Django 3.0.6 on 2020-05-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200524_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(null=True, upload_to='images/books_cover_pages/'),
        ),
    ]
