# Generated by Django 3.0.6 on 2020-05-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200524_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='images/books_cover_pages/'),
        ),
    ]
