# Generated by Django 3.0.6 on 2020-05-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_poll_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poller',
            field=models.ForeignKey(limit_choices_to={'is_author': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
